image: alpine:3.10

stages:
  - deploy

variables:
  TEST_RSA: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQ21GbGN6STFOaTFqZEhJQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJERjdFUG0xSQpWaUpFWkJtUWVqamg0ZEFBQUFFQUFBQUFFQUFBRVhBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFEOURZMXkvbWxrCmtBcEJiTFhkUDdMenBmbndjT2JlTGFSTTNUZE5VS0cyREdFckNFcmJvMmRtRkhNb01NR01ocEpQSFdHMHZUa1p3TW1aNUkKWEdjaUwwQzUzVEI4RDFmQ1lJb0lyQlFUZytuaGdDY1JXeWlqOHZkWnF3Ym96RXR5dGZZOG1xUU84WXZyUUQvaEQ0VlZJcgpzbXVJSER1SmtCdzdzeTR4Y3FBaVIxOW1NMnhKK1h6c1pYeFZEVkFlQUxPS1B3UFZUZSs4N3RCNkNBVDk3RGdCNFozWkNsCkVwQmNQUDRnS3dwU0ZhN1g1OG8weHRPYUxkVnhFU3gvNVFsRE9mdHNtTXFIOUVwbFRkWCtzbEphdkxCU3JJcHdiQ3IrcFEKT240U3JiR04rbmR3TnMwMTFBU29ma092eThaYzI3QkxlbEtKNjB1ZFRPT3F6SGVFMWp5L0FBQUQ0RVBobmw5SEF2dTY5UApmNnBHZHZhY3Vnd05pbjgwU01vWFA5Qk1kN1VZYVVwTUd3WEZ5aWVmOEJDdHpaaG1kTUdsMVpQM24vWTY2UFFUNnoyTHF3CkI1aENhK1RiVzNjemMreDFURFdqMXhZTWV1dVplWjZxUXBWS0F0R01tMHpNMkROV2JZbzZxK0RGSmlpT2JkUVBqcUc0UFgKSWdJSllZaU5GQUExUUlQTlFxYjVFOWROLzg5TjNHWU1CTXp5eGFidllKcXpUUnNpTzJvTm4rZFpOWTNvSDY2L2EyOGlyNQpvUzFhendrTlhuRkNkS2RCZW14b1kxTmYwVGdwbFZaSm05dklvNnY3d3pwcmNZNUpGQWc3emUwNGdvN294ZmdNeXIvWkRNCkl5blo3V0xDZjhXWmE2a3lKUDZBSUpjaGhqWnl1UE0zekt1Unh6dTg1YXZkdlZTQ0NFTmhlWTJBbk9GZExDSHJkMGVBN0cKalZGTzU2VERFN3pDV2VheDVsa2JhMUpLZGNDZ1FTVWpUNTAzK3djYkdnWllZOTNLMGUwZXdITGxSTlV4alBPM2g0RG0wQgpRNk9BRmUzb2ZRRUw4akFQZGtyemhJOE1ENGxoQkdOUGFTNVZWVHEyME5uTkVBOFh5OERyTHZUK1AzRWt1dzhsdmtHMWJuCm0zd2I3YjZYeEVkdzAvUEZwRUFaUE8rZHV4TjVrVDRVd0krcVFXM2J3UzlTTzEweDI1YTgvc25KWkx6blVMK2xBRk0yeFMKcUVJNDBCdGowemduNW9QQnFZV1lBamMvYk9xRGp5R0dGdzVjMkJveC96ZmRHSnErTG1pMGYvT1VrSUdGd1QydVhHNmR6aApCaEhYRUtEOXVVMTBURStlS0Q0RU4wU2VOa2FwMEQxVjZJMXc4d0ppRmtQbmJkbkJKM2pzMThFS2tLeDV5RnpIc2V6QmhQCkhqYzQ2THBWcFA5ZUxNNnZJWFFhL3VKMENoQVB6Q3cza2s5QlVzVEdKbEdzZnFsQi8zcS85UUZqSlpXMU9QVDhjMnp6eDAKQW41NG5nYjNBSzFJMXZubklOV3RZWkQ3eStlODVFRnpVdzdzclFjVXI4c0xyYkVTQldjaStkSlBISm9kMkl2ZG1Vb2sxUQpmVkZqWEEzaGZPMkwwNUVrSzhJMHVKcHFyRzJwYk91ZmU2clpIU0ttbXhKS1Z1WDRrcEM1cEFtOEk1c29qcEE5ZmhtOEU0CngzclAvNjBBdU5XTG0ya3NBTVk0ei80UUZaa3ZJRlhIQ3BiNVZGdXBmcXpFejgvV0hoSWwzTWRseC9PdVFxTEtzMGc4c3cKdnkzYkdNZW9aMGV1Rldicm9YZ2pRaGYzMit2WWdWMytnank0WHIyNUgycVlHZ2FvS2V1OW1RaHRxbmk2MmdON3JKSkp4SgpqMFV3U0lPWDU2OU10OG1zVFE3WHJtMHVOMkpsNTRNbUQ1WU9LOE5Vc1Q5dlkyYVBxN0pjSmUrN2M1aFgzQUkrQzJrQlgyCjhBd0FxZU1Mem9xa2t2NHVXalJ3NlFnWnhUVmUvV2VCQXZ1QThhTjJvVzQzbytNd0k1ejNrdHRZaFBzQjlwLzVTR1F0d0cKUUM5UEVLVHRsWXdYckZPNWc3dkMvOU1NKzlrOVRxdEQ5N1NXdlJXaC9LVU9LRHhOMnI3UXFHMVFYTmJWTmthMUVBUndnMwphNHpHT1ZuK0pwaXMrR3oyVloxL3ZYZHVQdXNLRWtDeVphd0ROcFlXc3E4UzhsMVNuUwotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K"
  TEST_RSA_KEY: "hN5aola5gk7v15EUoJOIb2hn6fp6fbh7"

deploy_source:
  stage: deploy
  before_script:
    - apk update
    - apk add openssh rsync
    - mkdir /root/.ssh
    - chmod 700 /root/.ssh
    - echo $TEST_RSA | base64 -d > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    # - echo "${TEST_HOST}" > /root/.ssh/known_hosts
    # - chmod 644 /root/.ssh/known_hosts
  script:
    - echo $TEST_RSA
    - ls -alR /root/.ssh/
    - cat /root/.ssh/*
    - ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa root@167.71.33.154 cat /root/test.txt
    # - cat test.txt
  # only:
  #   - master


ssh -o StrictHostKeyChecking=no root@104.248.241.99 <(echo "hN5aola5gk7v15EUoJOIb2hn6fp6fbh7\n")

sshpass -p'hN5aola5gk7v15EUoJOIb2hn6fp6fbh7' ssh -o StrictHostKeyChecking=no root@104.248.241.99 ls -la

sshpass -e ssh -o StrictHostKeyChecking=no root@104.248.241.99 ls -la


docker build --build-arg